[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--no-ignore-optional"
[context.production.environment]
  NODE_VERSION = "14.x"
[context.production.environment]
  PYTHON_VERSION = "3.8"